//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstates
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.BuyerEstates = new HashSet<BuyerEstates>();
            this.SellerEstates = new HashSet<SellerEstates>();
        }
    
        public string clientId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
    
        public virtual ICollection<BuyerEstates> BuyerEstates { get; set; }
        public virtual ICollection<SellerEstates> SellerEstates { get; set; }
    }
}
