//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstates
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public string BuyerEstateId { get; set; }
        public string SellerEstateId { get; set; }
        public string Status { get; set; }
    
        public virtual BuyerEstates BuyerEstates { get; set; }
        public virtual SellerEstates SellerEstates { get; set; }
    }
}
