//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstates
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighborhood
    {
        public Neighborhood()
        {
            this.Streets = new HashSet<Streets>();
        }
    
        public int HoodID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string HoodName { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<Streets> Streets { get; set; }
    }
}
